name = "academinimalistic"
license = "MIT"
licenselink = "https://github.com/thibautbenjamin/hugotheme/blob/master/LICENSE"
description = "A simple theme for my personal website"
homepage = ""
tags = [ "personal", "academic" ]
features = [ "fontawesome" ]
min_version = "0.41"

[author]
  name = "Thibaut Benjamin"
  homepage = "https://thibautbenjamin.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
